# Generated by Django 5.2.17 on 2026-08-24 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Menu identifier (e.g., 'Main Menu', 'Footer')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-friendly identifier", unique=True),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Enable/disable this menu"
                    ),
                ),
                (
                    "max_depth",
                    models.IntegerField(
                        default=3, help_text="Maximum nesting depth for menu items"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Internal notes about this menu"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Display text for menu item", max_length=255
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("page", "Wagtail Page"),
                            ("external", "External URL"),
                            ("custom", "Custom URL"),
                        ],
                        default="page",
                        help_text="Type of link this menu item points to",
                        max_length=20,
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="URL (for 'External URL' or 'Custom URL' link types)",
                        max_length=500,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class (e.g., 'fas fa-home' for Font Awesome)",
                        max_length=100,
                    ),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=False, help_text="Open link in new tab/window"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Show/hide this menu item"
                    ),
                ),
                (
                    "custom_css_class",
                    models.CharField(
                        blank=True,
                        help_text="Optional CSS classes for styling",
                        max_length=255,
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="navigation.menu",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select a page (for 'Wagtail Page' link type)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for top-level items",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="navigation.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item",
                "verbose_name_plural": "Menu Items",
                "ordering": ["sort_order"],
            },
        ),
    ]
