# Generated by Django 5.2.17 on 2026-08-24 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("gemini", "Google Gemini"),
                            ("groq", "Groq"),
                            ("ollama", "Ollama"),
                            ("local_openai", "Local OpenAI-Compatible"),
                        ],
                        max_length=32,
                    ),
                ),
                ("base_url", models.URLField(blank=True)),
                (
                    "api_key_env_var",
                    models.CharField(
                        blank=True,
                        help_text="Environment variable name that stores the provider API key.",
                        max_length=120,
                    ),
                ),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("timeout_seconds", models.PositiveIntegerField(default=60)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional tenant scope. Leave empty for global provider.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_providers",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Provider",
                "verbose_name_plural": "AI Providers",
                "ordering": ["name"],
                "unique_together": {("tenant", "slug")},
            },
        ),
        migrations.CreateModel(
            name="EmbeddingModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                ("model_name", models.CharField(max_length=160)),
                ("vector_size", models.PositiveIntegerField(default=1536)),
                ("batch_size", models.PositiveIntegerField(default=32)),
                ("model_kwargs", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding_models",
                        to="ai_providers.aiproviderconfig",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding_models",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Embedding Model",
                "verbose_name_plural": "Embedding Models",
                "ordering": ["name"],
                "unique_together": {("provider", "model_name"), ("tenant", "slug")},
            },
        ),
        migrations.CreateModel(
            name="LLMModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                ("model_name", models.CharField(max_length=160)),
                ("temperature", models.FloatField(default=0.2)),
                ("max_tokens", models.PositiveIntegerField(default=1024)),
                ("top_p", models.FloatField(default=1.0)),
                ("frequency_penalty", models.FloatField(default=0.0)),
                ("presence_penalty", models.FloatField(default=0.0)),
                ("supports_streaming", models.BooleanField(default=True)),
                ("model_kwargs", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_models",
                        to="ai_providers.aiproviderconfig",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_models",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Model",
                "verbose_name_plural": "LLM Models",
                "ordering": ["name"],
                "unique_together": {("provider", "model_name"), ("tenant", "slug")},
            },
        ),
    ]
