# Generated by Django 5.2.17 on 2026-08-24 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_providers", "0001_initial"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiproviderconfig",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="Optional direct API key for zero-touch admin setup.",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="AIProviderSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_provider_type",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("gemini", "Google Gemini"),
                            ("groq", "Groq"),
                            ("ollama", "Ollama"),
                            ("local_openai", "Local OpenAI-Compatible"),
                        ],
                        default="openai",
                        max_length=32,
                    ),
                ),
                ("openai_api_key", models.CharField(blank=True, max_length=255)),
                ("gemini_api_key", models.CharField(blank=True, max_length=255)),
                ("groq_api_key", models.CharField(blank=True, max_length=255)),
                (
                    "ollama_base_url",
                    models.URLField(blank=True, default="http://localhost:11434/v1"),
                ),
                (
                    "local_openai_base_url",
                    models.URLField(blank=True, default="http://localhost:8001/v1"),
                ),
                ("local_openai_api_key", models.CharField(blank=True, max_length=255)),
                ("allow_local_llm", models.BooleanField(default=True)),
                ("allow_openai", models.BooleanField(default=True)),
                ("allow_gemini", models.BooleanField(default=True)),
                ("allow_groq", models.BooleanField(default=True)),
                (
                    "default_embedding_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_embedding_settings",
                        to="ai_providers.embeddingmodelconfig",
                    ),
                ),
                (
                    "default_llm_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_llm_settings",
                        to="ai_providers.llmmodelconfig",
                    ),
                ),
                (
                    "default_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_provider_settings",
                        to="ai_providers.aiproviderconfig",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Provider Settings",
            },
        ),
    ]
