# Generated by Django 5.2.17 on 2026-08-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for knowledge base",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-friendly identifier", unique=True),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of knowledge base content"
                    ),
                ),
                (
                    "collection_name",
                    models.CharField(
                        help_text="Qdrant collection name", max_length=255, unique=True
                    ),
                ),
                (
                    "vector_size",
                    models.IntegerField(
                        default=1536,
                        help_text="Embedding vector dimension (default 1536 for OpenAI)",
                    ),
                ),
                (
                    "top_k",
                    models.IntegerField(
                        default=5, help_text="Number of documents to retrieve per query"
                    ),
                ),
                (
                    "similarity_threshold",
                    models.FloatField(
                        default=0.7, help_text="Minimum similarity score (0.0 - 1.0)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable/disable this knowledge base"
                    ),
                ),
                (
                    "document_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of documents in this knowledge base",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Base",
                "verbose_name_plural": "Knowledge Bases",
                "ordering": ["-created_at"],
            },
        ),
    ]
