# Generated by Django 5.2.17 on 2026-08-24 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional tenant scope. Leave empty for global knowledge base.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_bases",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="collection_name",
            field=models.CharField(help_text="Qdrant collection name", max_length=255),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="name",
            field=models.CharField(
                help_text="Display name for knowledge base", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="slug",
            field=models.SlugField(help_text="URL-friendly identifier"),
        ),
        migrations.AlterUniqueTogether(
            name="knowledgebase",
            unique_together={("tenant", "collection_name"), ("tenant", "slug")},
        ),
        migrations.CreateModel(
            name="QdrantConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                ("url", models.URLField(default="http://localhost:6333")),
                (
                    "api_key_env_var",
                    models.CharField(
                        blank=True,
                        help_text="Environment variable containing Qdrant API key.",
                        max_length=120,
                    ),
                ),
                ("prefer_grpc", models.BooleanField(default=False)),
                ("verify_tls", models.BooleanField(default=True)),
                ("timeout_seconds", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional tenant scope. Leave empty for global connection.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qdrant_connections",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qdrant Connection",
                "verbose_name_plural": "Qdrant Connections",
                "ordering": ["name"],
                "unique_together": {("tenant", "slug")},
            },
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="qdrant_connection",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional explicit connection. Uses default connection when empty.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="knowledge_bases",
                to="knowledge.qdrantconnection",
            ),
        ),
    ]
