# Generated by Django 5.2.17 on 2026-08-24 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0002_knowledgebase_tenant_and_more"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="qdrantconnection",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="Optional direct API key for zero-touch admin setup.",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="VectorDBSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qdrant_url",
                    models.URLField(blank=True, default="http://localhost:6333"),
                ),
                ("qdrant_api_key", models.CharField(blank=True, max_length=255)),
                ("qdrant_prefer_grpc", models.BooleanField(default=False)),
                ("qdrant_timeout_seconds", models.PositiveIntegerField(default=30)),
                ("auto_create_collections", models.BooleanField(default=True)),
                (
                    "default_knowledge_base",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_vector_kb_settings",
                        to="knowledge.knowledgebase",
                    ),
                ),
                (
                    "default_qdrant_connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_vector_db_settings",
                        to="knowledge.qdrantconnection",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vector DB Settings",
            },
        ),
    ]
