# Generated by Django 5.2.17 on 2026-08-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0003_qdrantconnection_api_key_vectordbsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("huggingface", "HuggingFace"),
                            ("openai", "OpenAI"),
                            ("azure_openai", "Azure OpenAI"),
                            ("ollama", "Ollama"),
                            ("local", "Local Models"),
                            ("custom", "Custom API"),
                        ],
                        default="default",
                        max_length=32,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        help_text="Embedding model identifier, e.g. text-embedding-3-small",
                        max_length=160,
                    ),
                ),
                ("embedding_dimensions", models.PositiveIntegerField(default=1536)),
                (
                    "best_use_case",
                    models.CharField(
                        blank=True,
                        help_text="One line describing when to pick this provider",
                        max_length=255,
                    ),
                ),
                (
                    "performance_rating",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Performance rating from 1 (basic) to 5 (excellent)",
                    ),
                ),
                (
                    "cost_indicator",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("low", "Low Cost"),
                            ("medium", "Medium Cost"),
                            ("high", "High Cost"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("online", "Online (Cloud)"),
                            ("offline", "Offline (Local)"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                (
                    "highlights",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Short bullet highlights shown on the provider card, e.g. ["Good general purpose embeddings"]',
                    ),
                ),
                (
                    "why_choose",
                    models.TextField(
                        blank=True,
                        help_text="Shown in the 'Why choose this provider?' help section",
                    ),
                ),
                (
                    "badge_recommended",
                    models.BooleanField(
                        default=False, verbose_name="Badge: Recommended"
                    ),
                ),
                (
                    "badge_cost_effective",
                    models.BooleanField(
                        default=False, verbose_name="Badge: Cost Effective"
                    ),
                ),
                (
                    "badge_fully_offline",
                    models.BooleanField(
                        default=False, verbose_name="Badge: Fully Offline"
                    ),
                ),
                (
                    "badge_fastest",
                    models.BooleanField(default=False, verbose_name="Badge: Fastest"),
                ),
                (
                    "badge_highest_accuracy",
                    models.BooleanField(
                        default=False, verbose_name="Badge: Highest Accuracy"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Used automatically when the uploader does not pick a profile",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Embedding Profile",
                "verbose_name_plural": "Embedding Profiles",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="vectordbsettings",
            options={
                "verbose_name": "Qdrant Dashboard",
                "verbose_name_plural": "Qdrant Dashboard",
            },
        ),
    ]
