# Generated by Django 5.2.17 on 2026-08-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0005_seed_embedding_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="embeddingprofile",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="Optional API key for this provider",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="embeddingprofile",
            name="api_key_env_var",
            field=models.CharField(
                blank=True,
                help_text="Optional environment variable name holding the API key instead",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="embeddingprofile",
            name="base_url",
            field=models.URLField(
                blank=True,
                help_text="Provider API endpoint used for the availability check, e.g. https://api.openai.com/v1",
            ),
        ),
        migrations.AddField(
            model_name="embeddingprofile",
            name="connection_timeout_seconds",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="embeddingprofile",
            name="proxy_url",
            field=models.URLField(
                blank=True,
                help_text="Optional proxy URL used only when checking this provider's connectivity",
            ),
        ),
    ]
