# Generated by Django 6.0.8 on 2026-08-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_embeddingprofile_show_on_dashboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vectordbsettings',
            options={'verbose_name': 'Vector DB', 'verbose_name_plural': 'Vector DB'},
        ),
    ]
