# Generated by Django 5.2.17 on 2026-08-24 07:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_create_homepage"),
        ("knowledge", "0001_initial"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page", "verbose_name_plural": "Home Pages"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="canonical_url",
            field=models.URLField(
                blank=True, help_text="Canonical URL for duplicate page management"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Page description for search engines",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_text",
            field=models.CharField(
                blank=True,
                help_text="Call-to-action button text",
                max_length=100,
                verbose_name="Hero CTA Text",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_url",
            field=models.CharField(
                blank=True,
                help_text="URL for CTA button",
                max_length=500,
                verbose_name="Hero CTA URL",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Background image for hero section",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_subtitle",
            field=models.CharField(
                blank=True, help_text="Subtitle under hero title", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(
                blank=True, help_text="Large hero title at page top", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="Description for social media sharing",
                max_length=255,
                verbose_name="Open Graph Description",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image for social media sharing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Open Graph Image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="Title for social media sharing",
                max_length=255,
                verbose_name="Open Graph Title",
            ),
        ),
        migrations.CreateModel(
            name="AIAssistantPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Page description for search engines",
                        max_length=255,
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        help_text="Title for social media sharing",
                        max_length=255,
                        verbose_name="Open Graph Title",
                    ),
                ),
                (
                    "og_description",
                    models.CharField(
                        blank=True,
                        help_text="Description for social media sharing",
                        max_length=255,
                        verbose_name="Open Graph Description",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Canonical URL for duplicate page management",
                    ),
                ),
                (
                    "assistant_name",
                    models.CharField(
                        blank=True, help_text="Name of AI assistant", max_length=255
                    ),
                ),
                (
                    "assistant_description",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Description shown above chat"
                    ),
                ),
                (
                    "welcome_message",
                    models.TextField(
                        blank=True, help_text="Initial message shown to user"
                    ),
                ),
                (
                    "show_knowledge_selector",
                    models.BooleanField(
                        default=False, help_text="Allow user to select knowledge bases"
                    ),
                ),
                (
                    "allow_anonymous",
                    models.BooleanField(
                        default=True, help_text="Allow anonymous users to chat"
                    ),
                ),
                (
                    "require_login",
                    models.BooleanField(
                        default=False, help_text="Require login to use chat"
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for social media sharing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Open Graph Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Assistant Page",
                "verbose_name_plural": "AI Assistant Pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="KnowledgeBasePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Page description for search engines",
                        max_length=255,
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        help_text="Title for social media sharing",
                        max_length=255,
                        verbose_name="Open Graph Title",
                    ),
                ),
                (
                    "og_description",
                    models.CharField(
                        blank=True,
                        help_text="Description for social media sharing",
                        max_length=255,
                        verbose_name="Open Graph Description",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Canonical URL for duplicate page management",
                    ),
                ),
                (
                    "is_listing",
                    models.BooleanField(
                        default=True,
                        help_text="Is this a listing page (vs detail page)?",
                    ),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        blank=True,
                        help_text="For detail pages: select knowledge base",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="knowledge.knowledgebase",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for social media sharing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Open Graph Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Base Page",
                "verbose_name_plural": "Knowledge Base Pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Page description for search engines",
                        max_length=255,
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        help_text="Title for social media sharing",
                        max_length=255,
                        verbose_name="Open Graph Title",
                    ),
                ),
                (
                    "og_description",
                    models.CharField(
                        blank=True,
                        help_text="Description for social media sharing",
                        max_length=255,
                        verbose_name="Open Graph Description",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Canonical URL for duplicate page management",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        help_text="Main headline for landing page", max_length=255
                    ),
                ),
                (
                    "subheadline",
                    models.CharField(
                        blank=True, help_text="Supporting headline", max_length=255
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero", 6),
                            ("richtext", 7),
                            ("image", 10),
                            ("image_text", 13),
                            ("cards", 19),
                            ("cta", 23),
                            ("tabs", 26),
                            ("accordion", 29),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            1: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"blank": True, "max_length": 255},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"blank": True, "max_length": 100},
                            ),
                            4: ("wagtail.blocks.URLBlock", (), {"blank": True}),
                            5: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 50,
                                    "help_text": "Background overlay opacity (0-100)",
                                    "max_value": 100,
                                    "min_value": 0,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("background_image", 0),
                                        ("title", 1),
                                        ("subtitle", 2),
                                        ("button_text", 3),
                                        ("button_url", 4),
                                        ("overlay_opacity", 5),
                                    ]
                                ],
                                {},
                            ),
                            7: ("home.blocks.RichTextBlock", (), {}),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Image caption",
                                    "max_length": 255,
                                },
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Alternative text for accessibility",
                                    "max_length": 255,
                                },
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 0), ("caption", 8), ("alt_text", 9)]],
                                {},
                            ),
                            11: ("wagtail.blocks.RichTextBlock", (), {}),
                            12: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Image Left"),
                                        ("right", "Image Right"),
                                    ]
                                },
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 0), ("text", 11), ("position", 12)]],
                                {},
                            ),
                            14: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"blank": True},
                            ),
                            15: ("wagtail.blocks.TextBlock", (), {"blank": True}),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 14),
                                        ("title", 1),
                                        ("text", 15),
                                        ("link_text", 3),
                                        ("link_url", 4),
                                    ]
                                ],
                                {},
                            ),
                            17: ("wagtail.blocks.ListBlock", (16,), {}),
                            18: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        (2, "2 Columns"),
                                        (3, "3 Columns"),
                                        (4, "4 Columns"),
                                    ]
                                },
                            ),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [[("cards", 17), ("columns", 18)]],
                                {},
                            ),
                            20: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                            21: ("wagtail.blocks.URLBlock", (), {}),
                            22: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("accent", "Accent"),
                                    ]
                                },
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 2),
                                        ("text", 15),
                                        ("button_text", 20),
                                        ("button_url", 21),
                                        ("button_style", 22),
                                    ]
                                ],
                                {},
                            ),
                            24: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 20), ("content", 11)]],
                                {},
                            ),
                            25: ("wagtail.blocks.ListBlock", (24,), {}),
                            26: ("wagtail.blocks.StructBlock", [[("tabs", 25)]], {}),
                            27: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 1), ("content", 11)]],
                                {},
                            ),
                            28: ("wagtail.blocks.ListBlock", (27,), {}),
                            29: ("wagtail.blocks.StructBlock", [[("items", 28)]], {}),
                        },
                        help_text="Landing page content blocks",
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        help_text="Primary call-to-action button text",
                        max_length=100,
                        verbose_name="CTA Text",
                    ),
                ),
                (
                    "cta_url",
                    models.CharField(
                        help_text="Target URL for CTA",
                        max_length=500,
                        verbose_name="CTA URL",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for social media sharing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Open Graph Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Landing Page",
                "verbose_name_plural": "Landing Pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="StandardPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Page description for search engines",
                        max_length=255,
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        help_text="Title for social media sharing",
                        max_length=255,
                        verbose_name="Open Graph Title",
                    ),
                ),
                (
                    "og_description",
                    models.CharField(
                        blank=True,
                        help_text="Description for social media sharing",
                        max_length=255,
                        verbose_name="Open Graph Description",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Canonical URL for duplicate page management",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 3),
                            ("richtext", 4),
                            ("quote", 7),
                            ("image", 11),
                            ("image_text", 14),
                            ("hero", 20),
                            ("cta", 25),
                            ("cards", 30),
                            ("columns", 33),
                            ("accordion", 36),
                            ("tabs", 39),
                            ("code", 42),
                            ("video", 44),
                            ("embed", 45),
                            ("ai_prompt", 50),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h1", "Heading 1"),
                                        ("h2", "Heading 2"),
                                        ("h3", "Heading 3"),
                                        ("h4", "Heading 4"),
                                    ]
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Heading text", "max_length": 255},
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Left"),
                                        ("center", "Center"),
                                        ("right", "Right"),
                                    ]
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("level", 0), ("text", 1), ("alignment", 2)]],
                                {},
                            ),
                            4: ("home.blocks.RichTextBlock", (), {}),
                            5: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"help_text": "Quote text"},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Attribution/author",
                                    "max_length": 255,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 5), ("attribution", 6), ("alignment", 2)]],
                                {},
                            ),
                            8: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Image caption",
                                    "max_length": 255,
                                },
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Alternative text for accessibility",
                                    "max_length": 255,
                                },
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 8), ("caption", 9), ("alt_text", 10)]],
                                {},
                            ),
                            12: ("wagtail.blocks.RichTextBlock", (), {}),
                            13: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Image Left"),
                                        ("right", "Image Right"),
                                    ]
                                },
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 8), ("text", 12), ("position", 13)]],
                                {},
                            ),
                            15: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                            16: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"blank": True, "max_length": 255},
                            ),
                            17: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"blank": True, "max_length": 100},
                            ),
                            18: ("wagtail.blocks.URLBlock", (), {"blank": True}),
                            19: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 50,
                                    "help_text": "Background overlay opacity (0-100)",
                                    "max_value": 100,
                                    "min_value": 0,
                                },
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("background_image", 8),
                                        ("title", 15),
                                        ("subtitle", 16),
                                        ("button_text", 17),
                                        ("button_url", 18),
                                        ("overlay_opacity", 19),
                                    ]
                                ],
                                {},
                            ),
                            21: ("wagtail.blocks.TextBlock", (), {"blank": True}),
                            22: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                            23: ("wagtail.blocks.URLBlock", (), {}),
                            24: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("accent", "Accent"),
                                    ]
                                },
                            ),
                            25: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 16),
                                        ("text", 21),
                                        ("button_text", 22),
                                        ("button_url", 23),
                                        ("button_style", 24),
                                    ]
                                ],
                                {},
                            ),
                            26: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"blank": True},
                            ),
                            27: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 26),
                                        ("title", 15),
                                        ("text", 21),
                                        ("link_text", 17),
                                        ("link_url", 18),
                                    ]
                                ],
                                {},
                            ),
                            28: ("wagtail.blocks.ListBlock", (27,), {}),
                            29: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        (2, "2 Columns"),
                                        (3, "3 Columns"),
                                        (4, "4 Columns"),
                                    ]
                                },
                            ),
                            30: (
                                "wagtail.blocks.StructBlock",
                                [[("cards", 28), ("columns", 29)]],
                                {},
                            ),
                            31: (
                                "wagtail.blocks.StreamBlock",
                                [[("text", 4), ("image", 11)]],
                                {"help_text": "Content for left column"},
                            ),
                            32: (
                                "wagtail.blocks.StreamBlock",
                                [[("text", 4), ("image", 11)]],
                                {"help_text": "Content for right column"},
                            ),
                            33: (
                                "wagtail.blocks.StructBlock",
                                [[("left_content", 31), ("right_content", 32)]],
                                {},
                            ),
                            34: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 15), ("content", 12)]],
                                {},
                            ),
                            35: ("wagtail.blocks.ListBlock", (34,), {}),
                            36: ("wagtail.blocks.StructBlock", [[("items", 35)]], {}),
                            37: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 22), ("content", 12)]],
                                {},
                            ),
                            38: ("wagtail.blocks.ListBlock", (37,), {}),
                            39: ("wagtail.blocks.StructBlock", [[("tabs", 38)]], {}),
                            40: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("python", "Python"),
                                        ("javascript", "JavaScript"),
                                        ("html", "HTML"),
                                        ("css", "CSS"),
                                        ("json", "JSON"),
                                        ("sql", "SQL"),
                                        ("bash", "Bash"),
                                        ("plaintext", "Plain Text"),
                                    ]
                                },
                            ),
                            41: ("wagtail.blocks.TextBlock", (), {}),
                            42: (
                                "wagtail.blocks.StructBlock",
                                [[("language", 40), ("code", 41)]],
                                {},
                            ),
                            43: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"help_text": "YouTube or Vimeo URL"},
                            ),
                            44: (
                                "wagtail.blocks.StructBlock",
                                [[("video_url", 43), ("caption", 16)]],
                                {},
                            ),
                            45: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                            46: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Section title",
                                    "max_length": 255,
                                },
                            ),
                            47: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Instruction text shown above input",
                                },
                            ),
                            48: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Leave blank to use default assistant",
                                    "max_length": 255,
                                },
                            ),
                            49: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Show source citations in response",
                                },
                            ),
                            50: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 46),
                                        ("instruction", 47),
                                        ("assistant_slug", 48),
                                        ("show_sources", 49),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Add content blocks using the editor",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for social media sharing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Open Graph Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Page",
                "verbose_name_plural": "Standard Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
