# Generated by Django 5.2.17 on 2026-08-24 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connectors", "0001_initial"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectorconfig",
            name="access_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="connectorconfig",
            name="token_env_var",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name="ConnectorSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jira_base_url", models.URLField(blank=True)),
                ("jira_access_token", models.CharField(blank=True, max_length=255)),
                ("jira_project_key", models.CharField(blank=True, max_length=80)),
                ("confluence_base_url", models.URLField(blank=True)),
                (
                    "confluence_access_token",
                    models.CharField(blank=True, max_length=255),
                ),
                ("confluence_cql", models.CharField(blank=True, max_length=255)),
                ("auto_sync_enabled", models.BooleanField(default=False)),
                ("sync_interval_minutes", models.PositiveIntegerField(default=60)),
                (
                    "default_confluence_connector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_confluence_setting",
                        to="connectors.connectorconfig",
                    ),
                ),
                (
                    "default_jira_connector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_jira_setting",
                        to="connectors.connectorconfig",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connector Settings",
            },
        ),
    ]
