# Generated by Django 5.2.17 on 2026-08-24 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="AI CMS", help_text="Official site name", max_length=255
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, help_text="Site tagline or slogan", max_length=255
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#007bff",
                        help_text="Primary brand color (hex format)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#6c757d",
                        help_text="Secondary brand color (hex format)",
                        max_length=7,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#fd7e14",
                        help_text="Accent brand color (hex format)",
                        max_length=7,
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#ffffff",
                        help_text="Page background color",
                        max_length=7,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#212529", help_text="Primary text color", max_length=7
                    ),
                ),
                (
                    "heading_font",
                    models.CharField(
                        default="'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
                        help_text="Font family for headings (CSS font-family value)",
                        max_length=100,
                    ),
                ),
                (
                    "body_font",
                    models.CharField(
                        default="'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
                        help_text="Font family for body text",
                        max_length=100,
                    ),
                ),
                (
                    "monospace_font",
                    models.CharField(
                        default="'Monaco', 'Courier New', monospace",
                        help_text="Font family for code/monospace text",
                        max_length=100,
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, help_text="Twitter profile URL"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, help_text="LinkedIn profile URL"),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, help_text="GitHub profile URL"),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, help_text="Facebook page URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, help_text="Instagram profile URL"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Contact email address", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=20
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Physical address")),
                (
                    "copyright_text",
                    models.CharField(
                        blank=True,
                        help_text="Copyright notice in footer",
                        max_length=255,
                    ),
                ),
                (
                    "favicon",
                    models.ForeignKey(
                        blank=True,
                        help_text="Favicon (ICO or PNG, 32x32px)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Site logo (PNG/SVG recommended)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "logo_white",
                    models.ForeignKey(
                        blank=True,
                        help_text="White version of logo (for dark backgrounds)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branding Settings",
                "verbose_name_plural": "Branding Settings",
            },
        ),
    ]
