# Generated by Django 5.2.17 on 2026-08-24 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_initial"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiassistant",
            name="agent_mode",
            field=models.CharField(
                choices=[
                    ("rag", "RAG Agent"),
                    ("llm_only", "LLM Only"),
                    ("hybrid", "Hybrid"),
                ],
                default="rag",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AssistantRuntimeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_agent_mode",
                    models.CharField(
                        choices=[
                            ("rag", "RAG Agent"),
                            ("llm_only", "LLM Only"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="rag",
                        max_length=20,
                    ),
                ),
                ("allow_anonymous_chat", models.BooleanField(default=True)),
                ("max_requests_per_minute", models.PositiveIntegerField(default=60)),
                (
                    "default_assistant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_assistant_settings",
                        to="conversations.aiassistant",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assistant Runtime Settings",
            },
        ),
    ]
